import Head from "next/head";
import React from "react";

const about = () => {
  return (
    <div>
      <Head>
        <title>About | Facebook Campaign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>About</h1>
    </div>
  );
};

export default about;
