import React, { useEffect } from "react";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Router from "next/router";

export default function Home() {
  useEffect(() => {
    // const {pathname} = Router
    // if(pathname == '/' ){
    // }
    Router.push("/campaign/");
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Facebook Campaign | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Home</h1>
    </div>
  );
}
