import Head from "next/head";
import React from "react";

const profile = () => {
  return (
    <div>
      <Head>
        <title>Profile | Facebook Campaign</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Profile</h1>
    </div>
  );
};

export default profile;
